agroProject3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conv_csv.urls')),
]

conv_csv/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path 
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home',),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(
        template_name='conv_csv/signin.html',
        authentication_form = LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view()
         , {'next_page': '/core'}, name='logout'),
    path('convert/', views.csv_to_shapefile, name='convert'),
    path('shpF/', views.csv_to_shapefile, name='shap'),
    
]

conv_csv/models.py
from django.db import models

# Create your models here.

conv_csv/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User 

INPUT_CLASS = 'w-full py-4 px-6 rounded-xl'

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': INPUT_CLASS,
        #'required': True,
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': INPUT_CLASS,
        #'required': True,
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': INPUT_CLASS,
        #'required': True,
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email Address',
        'class': INPUT_CLASS,
        #'required': True,
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password',
        'class': INPUT_CLASS,
        #'required': True,
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': INPUT_CLASS,
        #'required': True,
    }))
    

conv_csv/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from django.conf import settings
import os

from .forms import SignupForm

# Create your views here.
@login_required
def csv_to_shapefile(request):
    if request.method == 'POST':
        csv_file = request.FILES['csv_file']
        if not csv_file.name.endswith(".csv"):
            messages.error(request, 'File is not CSV type')
            return render(request, 'conv_csv/wrongFile.html')
        df = pd.read_csv(csv_file)
        geometry = [Point(xy) for xy in zip(df.Longitude, df.Latitude)]
        gdf = gpd.GeoDataFrame(df, geometry=geometry)
        shapefile_path = os.path.join(settings.MEDIA_ROOT, 'output.shp')
        gdf.to_file(shapefile_path, driver='ESRI Shapefile')
        return render(request, 'conv_csv/conversion_complete.html')
    else:
        return render(request, 'conv_csv/csv_to_shapefile.html')
    
def home(request):
    return render(request, 'conv_csv/home.html')

from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request, 'conv_csv/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
        
    form = SignupForm()
    context = {'form': form}
    return render(request, 'conv_csv/signup.html', context)

templates/_base.html
<!doctype html>
    <html>
        
        <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <script src="https://cdn.tailwindcss.com"></script>
           
            <title>{% block title %}{% endblock %} | Agro</title>

        </head>

        <body>
            <nav class="py-6 px-6 flex justify-between items-center w-full border-b border-gray-200">
                <div class="space-x-3">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'core:home' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl bg-gray-700"> Hi {{ user }}</a>
                        <a href="{% url 'core:home' %}" class="text-2xl font-semibold">Agro</a>
                    {% else %}
                        <a href="{% url 'core:home' %}" class="text-xl font-semibold">Agro</a>
                    {% endif %}
                </div>


                <div class="space-x-6">
                    <a href="{% url 'core:convert' %}" class="text-lg font-semibold hover:text-gray-500">Upload CSV</a>
                    <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                    {% if request.user.is_authenticated %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl bg-teal-700">Inbox</a>
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl bg-gray-700">Dashboard</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl bg-teal-700">Sign out</a>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl bg-teal-700">Sign up</a>
                        <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl bg-gray-700">Sign in</a>
                    {% endif %}
                </div>
            </nav>
            <div class="px-6 py-6">
                {% block content %}
                {% endblock %}
            </div>

            <footer class="mt-8 py-6 px-6 flex justify-between bg-gray-800">
                <div class="w-2/3 pr-10">
                    <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                    <p class="text-lg text-gray-500">Lorem ipsum bla bla bla.</p>
                </div>

                <div class="w-1/3">
                    <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                    <ul class="space-y-2">
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
                </div>
            </footer>
        </body>
    
    </html>

templates/conv_csv/conversion_complete.html
{% extends '_base.html' %}

{% block title %}Convert CSV{% endblock %}

{% block content %}
    <h1 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
        Conversion complete!
      </h1>
      
    
{% endblock %}

templates/conv_csv/csv_to_shapefile.html
{% extends '_base.html' %}

{% block title %}Convert CSV{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-2xl">Upload CSV files for conversion</h1>
    <form method="POST" enctype="multipart/form-data" class="form-horizontal mt-5">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="name" class="col-md-3 col-xs-12 control-label>File: </label>
            <div class="col-md-8">
                <input type="file" name="csv_file" id="csv_file" class="form-control">
            </div>
        </div>
        <div class="mt-5 flex justify-center items-center">
            <button type="submit" class="bg-teal-500 hover:bg-teal-700 text-white py-3 px-8 rounded-xl">
              Submit
            </button>
        </div>
                      
    </form>
    </div>
{% endblock %}

templates/conv_csv/home.html
{% extends '_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">WELCOME TO AGRO</h1>

    
</div>

{% endblock %}

templates/conv_csv/signin.html
{% extends '_base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}
           

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}  
                    {{ field.errors }}
                {% endfor %}
                    
                {{ form.non_field_errors }}          
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit</button>
    </form>
</div>

{% endblock content %}

templates/conv_csv/signup.html
{% extends '_base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}
               

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Confirm password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}  
                        {{ field.errors }}
                    {% endfor %}
                        
                    {{ form.non_field_errors }}          
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
                Submit</button>
        </form>
    </div>
{% endblock content %}

templates/conv_csv/wrongFile.html
{% extends '_base.html' %}

{% block title %}CSV to KML{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
        Wrong file! ONLY csv files are allowed!
      </h1>
      

    <div>
       <h1> <a href="{% url 'core:shap' %}">Try Again</a></h1>
    </div>
    
    </div>
{% endblock %}